#!/bin/bash
# get-convert-list
# Created Fri Feb  5 11:03:26 AKST 2016
# Copyright (C) 2016 by Raymond E. Marcil <marcilr@gmail.com>
#
# Script to build a list of repositories to create given a directory to start
# from in the hierarchical list of directories.
#

# ==============================================
# Configuration
# ==============================================

#
# Enable/disable debugging.
#
DEBUG=true


# ==============================================
# Binaries
# ==============================================
FIND=/usr/bin/find


# ==============================================
# Functions
# ==============================================

#
# debug()
# Output debugging text.
# INPUT: $1 - Text to output if DEBUG="
#
function debug {

  if [ ${DEBUG} = "true" ]; then
    echo "debug() ${1}"
  fi

}


#
# message()
# Display specified message passed as argument.
#
# INPUT
# =====
# Message to display as argument.
#
# RESULTS
# =======
# Displays argument to stdio.
#
function message {

  echo "${1}"

}

#
# usage()
# Display usage and exit.
#
function usage(){
  message "Usage: ${0} <local svn repo>"
  message "   -d | --debug        Enable debugging."
  message "   -h | --help         Create non-hierarchical repository."
  message "   <local svn repo>    Subversion repo directory in"
  message "                       repository hiearhierarchy to build"
  message "                       conversion list from."
}


#
# process-cli-args()
#
# Links
# =====
# How to process command-line args in bash scripts
# http://debaan.blogspot.com/2007/06/how-to-process-command-line-args-in.html
#
function process-cli-args(){

  debug "process-cli-args() START"

  # Display number of command line arguments
  debug "process-cli-args() number args=${#commandline_args[@]}"

  # Loop over command line arguments (in correct order).
  for ARG in "${commandline_args[@]}"; do
    case ${ARG} in
      "-d" | "--debug")
        DEBUG=true
        debug "DEBUG=true"
        ;;
      "-h" | "--help")
        usage
        exit 0
        ;;
      *)
        debug "process-cli-args() processing: ${ARG}"
        SVNPATH=${ARG}
        debug "process-cli-args() SNVPATH=${SVNPATH}"
        ;;
    esac
  done

  debug "process-cli-args() END"

} # end process-cli-args()



# ==============================================
# Main
# ==============================================
debug "git-repo-create START"

# Check argument count
ARGCOUNT=$#
debug "main: ARGCOUNT=$#"

# Print usage and abort if no arguments
if [ -z "$1" ]; then
  usage
  exit 1
fi

# Get copy of command line arguments
commandline_args=("$@")

# Process command line arguments
process-cli-args

debug "main: SVNPATH = ${SVNPATH}"
