#!/bin/bash
# svn-to-git
# Created Wed Jan 27 15:55:10 AKST 2016
# Copyright (C) 2016 by Raymond E. Marcil <marcilr@gmail.com>
#
# Convert subversion repository to git
#
# Usage:
#   svn-to-git <subversion repo to convert>
#

# ==============================================
# Configuration
# ==============================================
USERS=users.txt


# ==============================================
# Binaries
# ==============================================
AWK=/usr/bin/awk
GREP=/bin/grep
PERL=/usr/bin/perl
SED=/bin/sed
SORT=/usr/bin/sort
SVN=/usr/bin/svn
UNIQ=/usr/bin/uniq

