#!/bin/bash
# svn-to-git
# Created Wed Jan 27 15:55:10 AKST 2016
# Copyright (C) 2016 by Raymond E. Marcil <marcilr@gmail.com>
#
# Convert subversion repository to git
#
# Usage:
#   svn-to-git <subversion repo to convert>
#

# ==============================================
# Configuration
# ==============================================
USERS=users.txt


# ==============================================
# Binaries
# ==============================================
AWK=/usr/bin/awk
GREP=/bin/grep
PERL=/usr/bin/perl
SED=/bin/sed
SORT=/usr/bin/sort
SVN=/usr/bin/svn
UNIQ=/usr/bin/uniq


# ==============================================
# Functions
# ==============================================

#
# debug()
# Output debugging text.
# INPUT: $1 - Text to output if DEBUG="
#
function debug {

  if [ ${DEBUG} = "true" ]; then
    echo "debug() ${1}"
  fi

}


#
# message()
# Display specified message passed as argument.
#
# INPUT
# =====
# Message to display as argument.
#
# RESULTS
# =======
# Displays argument to stdio.
#
function message {

  echo ${1}

}


#
# usage()
# Display usage and exit.
#
function usage(){
  message "Usage: ${0}"
  message "   -d | --debug   Enable debugging."
  message "   -h | --help    Create non-hierarchical repository."
}

#
# process-cli-args()
#
# Links
# =====
# How to process command-line args in bash scripts
# http://debaan.blogspot.com/2007/06/how-to-process-command-line-args-in.html
#
function process-cli-args(){

  debug "process-cli-args(): START"

  # Display number of command line arguments
  debug "process-cli-args(): number args=${#commandline_args[@]}"

  # Loop over command line arguments (in correct order).
  for arg in "${commandline_args[@]}"; do
    case ${arg} in
      "-d" | "--debug")
        DEBUG=true
        debug "DEBUG=true"
        ;;
      "-h" | "--help")
        usage
        exit 0
        ;;
      *)
        ;;
    esac
  done

  debug "process-cli-args(): END"

}



# ==============================================
# Main
# ==============================================

# Check argument count
ARGCOUNT=$#

echo "ARGCOUNT: $#"
