#!/bin/bash
# svn-to-git-authors
# Created Wed Jan 27 15:23:43 AKST 2016
# Copyright (C) 2016 by Raymond E. Marcil <marcilr@gmail.com>
#
# Script to extract users from subversion repository to users.txt file.
# Run this inside an subversion checkout.
#
# The marcilr, and root users have entries in users.txt cleaned up
# automatically.
#
# Other auhtors will have to have name and email updated manually.
#
#
# Links
# =====
# 9.2 Git and Other Systems - Migrating to Git
# Git Pro, 2nd Edition (2014)
# https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git
#
# Creating a svn.authorsfile when migrating from subversion to git
# Has subversion user extraction script that I like.
# http://technicalpickles.com/posts/creating-a-svn-authorsfile-when-migrating-from-subversion-to-git/
#

# ==============================================
# Configuration
# ==============================================
OUTFILE=users.txt


# ==============================================
# Binaries
# ==============================================
AWK=/usr/bin/awk
GREP=/bin/grep
PERL=/usr/bin/perl
SED=/bin/sed
SORT=/usr/bin/sort
SVN=/usr/bin/svn
UNIQ=/usr/bin/uniq


#
# Get users.txt from subversion repository in current working directory.
#
# This yields users.txt with:
#   <author>marcilr</author>
#   <author>root</author>
#
# Not terrible helpful.
#
# Git and Other Systems - Migrating to Git
# Git Pro, 2nd Edition (2014)
# https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git
#
#${SVN} log --xml | ${GREP} author | ${SORT} -u | ${PERL} -pe 's/.*&gt;(.*?)&lt;.*/$1 = /' > ${OUTFILE}

# Remove prior users.txt as needed:
rm -f ${OUTFILE}

#
# Creating a users.txt for use when migrating from subversion to git
#
# Links
# =====
# Creating a svn.authorsfile when migrating from subversion to git
# http://technicalpickles.com/posts/creating-a-svn-authorsfile-when-migrating-from-subversion-to-git/
#
AUTHORS=$(${SVN} log -q | ${GREP} -e '^r' | ${AWK} 'BEGIN { FS = "|" } ; { print $2 }' | ${SORT} | ${UNIQ})
for AUTHOR in ${AUTHORS}; do
  echo "${AUTHOR} = NAME <USER@DOMAIN>" >> ${OUTFILE}
done


# Clean up known users in users.txt file
${SED} -i 's/marcilr = NAME <USER@DOMAIN>/marcilr = Raymond Marcil <marcilr@gmail.com>/g' ${OUTFILE}
${SED} -i 's/root = NAME <USER@DOMAIN>/root = root <root@localhost>/g' ${OUTFILE}
