#!/bin/bash
# svn-to-git-convert
# Created Wed Jan 27 15:55:10 AKST 2016
# Copyright (C) 2016 by Raymond E. Marcil <marcilr@gmail.com>
#
# Convert subversion repository to git
#
# Usage:
#   svn-to-git <subversion repo to convert>
#
#
# Links
# =====
# 9.2 Git and Other Systems - Migrating to Git
# Git Pro, 2nd Edition (2014)
# https://git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git
#
# Cleanly Migrate Your Subversion Repository To a GIT Repository
# http://jonmaddox.com/2008/03/05/cleanly-migrate-your-subversion-repository-to-a-git-repository/
#
# git-svn(1) Manual Page
# git-svn - Bidirectional operation between a Subversion repository and git
# git --local-branching-on-the-cheap
# https://git-scm.com/docs/git-svn/1.7.7.2
#

# ==============================================
# Configuration
# ==============================================

#
# Enable/disable debugging.
#
DEBUG=true


# ==============================================
# Binaries
# ==============================================
AWK=/usr/bin/awk
GIT=/usr/bin/git
GREP=/bin/grep
PERL=/usr/bin/perl
RM=/bin/rm
SED=/bin/sed
SORT=/usr/bin/sort
SVN=/usr/bin/svn
UNIQ=/usr/bin/uniq


# ==============================================
# Functions
# ==============================================

#
# debug()
# Output debugging text.
# INPUT: $1 - Text to output if DEBUG="
#
function debug {

  if [ ${DEBUG} = "true" ]; then
    echo "debug() ${1}"
  fi

}


#
# message()
# Display specified message passed as argument.
#
# INPUT
# =====
# Message to display as argument.
#
# RESULTS
# =======
# Displays argument to stdio.
#
function message {

  echo ${1}

}


#
# usage()
# Display usage and exit.
#
function usage(){
  message "Usage: ${0} <authors> <subversion repo>"
  message "   -d | --debug   Enable debugging."
  message "   -h | --help    Create non-hierarchical repository."
}

#
# process-cli-args()
#
# Links
# =====
# How to process command-line args in bash scripts
# http://debaan.blogspot.com/2007/06/how-to-process-command-line-args-in.html
#
function process-cli-args(){

  debug "process-cli-args() START"

  # Display number of command line arguments
  debug "process-cli-args() number args=${#commandline_args[@]}"

  # Loop over command line arguments (in correct order).
  for ARG in "${commandline_args[@]}"; do
    case ${ARG} in
      "-d" | "--debug")
        DEBUG=true
        debug "DEBUG=true"
        ;;
      "-h" | "--help")
        usage
        exit 0
        ;;
      *)
        debug "process-cli-args() processing: ${ARG}"
       #
       # If AUTHORS is set save SVNREPO
       #
       # How do I check if a variable exists in bash?
       # http://unix.stackexchange.com/questions/212183/how-do-i-check-if-a-variable-exists-in-bash
       #
       if [ -v AUTHORS ]; then
            SVNREPO=${ARG}
            debug "process-cli-args() SVNREPO=${SVNREPO}"
        else
            AUTHORS=${ARG}
            debug "process-cli-args() AUTHORS=${AUTHORS}"
        fi
        ;;
    esac
  done

  debug "process-cli-args() END"

} # end process-cli-args()



# ==============================================
# Main
# ==============================================

# Check argument count
ARGCOUNT=$#
debug "main: ARGCOUNT=$#"

# Abort with usage if there are not 2 arguments
if [ ${ARGCOUNT} != 2 ]; then
  usage
  exit 1
fi

# Get copy of command line arguments
commandline_args=("$@")

# Process command line arguments
process-cli-args

debug "main: AUTHORS = ${AUTHORS}"
debug "main: SVNREPO = ${SVNREPO}"

# Verify that AUTHORS file exists
if [ -f ${AUTHORS} ]; then
  debug "main: Found ${AUTHORS}"
else
  message "${AUTHORS} not found, aborting."
  exit 1
fi

# Get REPO name from end of SVNREPO string
REPO=`echo ${SVNREPO} | sed 's:.*/::g'`
debug "main: REPO = ${REPO}"

# Check if REPO exists already
if [ -d ${REPO} ]; then
  message "${REPO} directory exists already, aborting."
  exit 1
fi

#
# Build git command to clone subversion repo as git repo
#
# Options:
# --authors-file     If this option is specified and git svn encounters an
#                    SVN committer name that does not exist in the authors-file,
#                    git svn will abort operation.  The user will then have to
#                    add the appropriate entry.  Re-running the previous git
#                    svn command after the authors-file is modified should
#                    continue operation.
#                    -- git-scm.com/docs/git-svn/1.7.7.2
#
# --no-metadata      This flag tells GIT to leave all the SVN details behind
#                    (not the commit log).
#                    -- jonmaddox.com/
#
# -- git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git
#
CMD="${GIT} svn clone ${SVNREPO}"
CMD+=" --authors-file=${AUTHORS}"
CMD+=" --no-metadata"
CMD+=" ${REPO}"

debug "main: CMD=${CMD}"


# Execute command to clone subversion repo as git repo
debug "main: Executing: ${CMD}"
eval "${CMD}"

#
# Do a bit of post-import cleanup.  For one thing, you should
# clean up the weird references that git svn set up. First you'll move the
# tags so they're actual tags rather than strange remote branches, and then
# you'll move the rest of the branches so they're local.
# -- git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git
#

CMD="cd ${REPO}; cp -Rf .git/refs/remotes/origin/tags/* .git/refs/tags/"
debug "main: Executing: ${CMD}"
eval "${CMD}"

CMD="${RM} -Rf .git/refs/remotes/origin/tags"
debug "main: Executing: ${CMD}"
eval "${CMD}"


#
# Next, move the rest of the references under refs/remotes to be local branches:
# -- git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git
#
CMD="cp -Rf .git/refs/remotes/origin/* .git/refs/heads/"
debug "main: Executing: ${CMD}"
eval "${CMD}"

CMD="${RM} -Rf .git/refs/remotes/origin"
debug "main: Executing: ${CMD}"
eval "${CMD}"

#
# It may happen that you'll see some extra branches which are suffixed by
# @xxx (where xxx is a number), while in Subversion you only see one branch.
# This is actually a Subversion feature called "peg-revisions", which is
# something that Git simply has no syntactical counterpart for.  Hence, git svn
# simply adds the svn version number to the branch name just in the same way as
# you would have written it in svn to address the peg-revision of that branch.
# If you do not care anymore about the peg-revisions, simply remove them using
# -- git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git
#
CMD="${GIT} branch -d"
debug "main: Executing: ${CMD}"
eval "${CMD}"

#
# There's one last thing to clean up.  Unfortunately, git svn creates an extra
# branch named trunk, which maps to Subversion's default branch, but the trunk
# ref points to the same place as master.  Since master is more idiomatically
# Git, here's how to remove the extra branch:
# -- git-scm.com/book/en/v2/Git-and-Other-Systems-Migrating-to-Git
#
CMD="${GIT} branch -d trunk"
debug "main: Executing: ${CMD}"
eval "${CMD}"
