#!/bin/bash
# test
# Created Thu Jan 28 14:33:05 AKST 2016
# Copyright (C) 2016 by Raymond E. Marcil <marcilr@gmail.com>
#
# Test driver for svn-to-git
#

# =====================================
# Configuration
# =====================================

#
# Enable/disable debugging.
#
DEBUG=true

# Authors file generated with svn-to-git-authors
AUTHORS=./authors.txt

# Subversion repo to convert to git
REPO=svn+ssh://home/data/svnroot/software/daemons/ntp/ntp


# =====================================
# Binaries
# =====================================
SUBVERSION=/usr/bin/svn
SVNTOGIT=./svn-to-git


# =====================================
# Functions
# =====================================

#
# debug()
# Output debugging text.
# INPUT: $1 - Text to output if DEBUG="
#
function debug {

  if [ ${DEBUG} = "true" ]; then
    echo "debug() ${1}"
  fi

}

#
# message()
# Display specified message passed as argument.
#
# INPUT
# =====
# Message to display as argument.
#
# RESULTS
# =======
# Displays argument to stdio.
#
function message {

  echo ${1}

}


# =====================================
# Main
# =====================================

# Execute with no arguments
message "Execute with no arguments"
${SVNTOGIT}

message
message "Execute with arguments"
# Execute svn-to-git
${SVNTOGIT} ${AUTHORS} ${REPO}
