#!/bin/bash
# test
# Created Thu Jan 28 14:33:05 AKST 2016
# Copyright (C) 2016 by Raymond E. Marcil <marcilr@gmail.com>
#
# Test driver for svn-to-git
#

# =====================================
# Configuration
# =====================================
AUTHORS=./authors.txt
REPO=svn+ssh://home/data/svnroot/software/daemons/ntp/ntp

# =====================================
# Binaries
# =====================================
SUBVERSION=/usr/bin/svn
SVNTOGIT=./svn-to-git
