#!/bin/bash
# test-github-push
# Created Tue Feb  2 09:08:24 AKST 2016
# Copyright (C) 2016 by Raymond E. Marcil <marcilr@gmail.com>
#
# Test github-push to push local git repo to github.
#


# ==============================================
# Configuration
# ==============================================

#
# Enable/disable debugging.
#
DEBUG=true

# Local git repository to push to github
GITREPO=gci

# GitHub repository to create and push to
GITHUBREPO=git-gci

# ==============================================
# Binaries
# ==============================================
GITHUBPUSH=github-push

# ==============================================
# Functions
# ==============================================

#
# debug()
# Output debugging text.
# INPUT: $1 - Text to output if DEBUG="
#
function debug {

  if [ ${DEBUG} = "true" ]; then
    echo "debug() ${1}"
  fi

}


#
# message()
# Display specified message passed as argument.
#
# INPUT
# =====
# Message to display as argument.
#
# RESULTS
# =======
# Displays argument to stdio.
#
function message {

  echo "${1}"

}


# ==============================================
# Main
# ==============================================

debug "main: GITREPO = ${GITREPO}"
debug "main: GITHUBREPO = ${GITHUBREPO}"

# Call github-push to create new github repo and push local git repo to it.
CMD="${GITHUBPUSH} ${GITREPO} ${GITHUBREPO}"
message "Executing: ${CMD}"
eval "${CMD}"
