#!/bin/bash
# test-svn-to-git-home
# Created Mon Feb  1 15:44:18 AKST 2016
# Copyright (C) 2016 by Raymond E. Marcil <marcilr@gmail.com>
#
# Test svn-git-conversion of subversion repo to git repo.
#

# ==============================================
# Configuration
# ==============================================

#
# Enable/disable debugging.
#
DEBUG=true

AUTHORS=authors.txt


#SVNPATH=svn+ssh://home/data/svnroot/gci/gci
#GITPATH=ssh://marcilr@home/data/git/gci


# ==============================================
# Binaries
# ==============================================
SED=/bin/sed
SVN=/usr/bin/svn
SVNTOGIT=./svn-to-git
SVNTOGITAUTHORS=svn-to-git-authors

# ==============================================
# Functions
# ==============================================

#
# debug()
# Output debugging text.
# INPUT: $1 - Text to output if DEBUG="
#
function debug {

  if [ ${DEBUG} = "true" ]; then
    echo "debug() ${1}"
  fi

}


#
# message()
# Display specified message passed as argument.
#
# INPUT
# =====
# Message to display as argument.
#
# RESULTS
# =======
# Displays argument to stdio.
#
function message {

  echo "${1}"

}


# ==============================================
# MAIN
# ==============================================


# Build conversion command
CMD="${SVNTOGIT} ${SVNPATH} ${GITPATH}"
debug "Executing: ${CMD}"

# Execute conversion command
eval "${CMD}"
